### ISSUE TITLE
Add support to Guttenberg

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Open-Reports#1]
Once https://github.com/SOBotics/CopyPastor/pull/14 is merged, CP will have a new [endpoint](https://github.com/SOBotics/CopyPastor#get-postspending) to return the posts which have no feedback. 

Calling the API would return something like

    { "posts": [ 1, 2, 3], "status": "success"} 

which implies links to http://copypastor.sobotics.org/posts/1, http://copypastor.sobotics.org/posts/2 and http://copypastor.sobotics.org/posts/3 must be shown.

**Comment by BaumMitAugen** [comment]
You can now get links to Gutty reports by appending `guttenberg` to the open commands. `fa guttenberg` and `ir guttenberg` also work.
