### ISSUE TITLE
Let <10k plops use Sentinel to see deleted posts

### ISSUE THREAD

**Issue by LW001** [SOBotics/Open-Reports#2]
As it currently stands, plebs can't use OpenReports to review deleted posts and give Feedback on them,  mostly resulting in using [Batty fetch](https://chat.stackoverflow.com/rooms/111347/conversation/batty-learns-how-to-use-links) to see sentinel links with deleted post content.

I'd say keep `open` as it is but add an argument to it that includes deleted posts (`open [d[elected]]` maybe I don't know). Links will come with the lovely help of Sentinel which has the GET /posts/aid/{postid} redirect.

Example: http://www.stackoverflow.com/a/42647791 > https://sentinel.erwaysoftware.com/posts/aid/42647791 > https://sentinel.erwaysoftware.com/posts/23133

**Comment by BaumMitAugen** [comment]
You can now get sentinel links instead of regular site links by appending `sentinel` to the open commands. Also works with `fa`.
