### ISSUE TITLE
New alias for open guttenberg

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Open-Reports#4]
Can we have an additional `@hou o g` as an alias for `@hou open guttenberg`?

**Comment by BaumMitAugen** [comment]
Done. You can use 'g' instead of 'guttenberg' now in every command. Also 's' is synonym for sentinel now.

I will probably rework the commands to be somewhat more sane in the future, a rewrite of the entire bot is in order anyway.
